name: Build iOS IPAs (Fresh)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Artifact iOS (Manual)
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set FLUTTER_ROOT
        run: echo "FLUTTER_ROOT=$(flutter --version --machine | grep -o 'flutterRoot.*' | cut -d: -f2 | tr -d '\",}')" >> $GITHUB_ENV

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: ios

      - name: Prepare CocoaPods
        run: gem install cocoapods

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios
          pod install

      - name: Build Unsigned IPA
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../Nudge-Unsigned.ipa Payload
          cd ../../..

      - name: Inject Team ID
        run: |
          sed -i '' "s/USER_TEAM_ID/${{ secrets.APPLE_TEAM_ID }}/g" ios/Runner.xcodeproj/project.pbxproj

      - name: Build and Sign IPA (Development)
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
        run: |
          cd ios
          bundle exec fastlane build

      - name: Upload IPAs
        uses: actions/upload-artifact@v4
        with:
          name: nudge-ios-artifacts-manual
          path: |
            build/Nudge-Unsigned.ipa
            build/ios/ipa/Nudge.ipa
